# fly.toml app configuration file generated for backend-quiet-frog-5967 on 2025-07-13T08:55:38+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-quiet-frog-5967'
primary_region = 'jnb'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false # Change this to false
  auto_start_machines = true
  min_machines_running = 1   # Change this to 1 (or more)
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1